name: Production Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Depoyu Çek
      uses: actions/checkout@v3

    - name: Java 17 Kurulumu
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Android SDK Hazırla
      uses: android-actions/setup-android@v3

    - name: APK Derle (Cache Kapalı - Güvenli Mod)
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2
        cache-disabled: true
        arguments: assembleDebug --stacktrace --info

    - name: APK'ları Topla
      uses: actions/upload-artifact@v4
      with:
        name: UrlDownloader-APKs
        path: app/build/outputs/apk/debug/*.apk
